version: '3'

tasks:
  build:
    cmds:
      - docker compose build
  up:
    cmds:
      - docker compose up -d

  install:
    cmds:
      - docker run --rm -v $PWD:/app -w /app node:22-alpine yarn